services:
  postgres:
    image: postgres:latest
    container_name: "${STACK_NAME}-postgres"
    hostname: "${STACK_NAME}-postgres"
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: "${STACK_NAME}-rabbitmq"
    container_name: "${STACK_NAME}-rabbitmq"
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - rabbitmq3:/var/lib/rabbitmq/
      # - ./docker_data/rabbitmq/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=123456aA@

volumes:
  postgres:
  rabbitmq3:
