packages:
#  - "apps/nestjs"
  - "shared/*"
  #  ________ Projects MAIN ________
  - "projects/main/apps/proxy-sls"
  - "projects/main/apps/slack-sls"
  #  ________ Projects BINANCE ________
#  - "projects/binance/apps/api"
  #  ________ Projects STOCK ________
  - "projects/stock/apps/api"
  - "projects/stock/apps/frontend"
  - "projects/stock/packages/*"
