packages:
#  - "apps/nextjs"
  - "shared/eslint-config-custom-react"
  - "shared/eslint-config-server"
  - "shared/tsconfig"
  - "shared/chitility"
  - "shared/web-base"
  #  ________ Projects MAIN ________
  #- "projects/main/apps/proxy-sls"
  #- "projects/main/apps/slack-sls"
  #  ________ Projects STOCK ________
#  - "projects/stock/apps/api"
  - "projects/stock/apps/web"
  - "projects/stock/packages/*"
