import { DataValueExtension } from 'chitility/dist/lib/extension/data-value-extension';
export default DataValueExtension.resolve('ROUTES', {
  CART: '/cart',
  MY_ACCOUNT: '/my-account',
  ACCOUNT_LOGIN: '/account-login',
  ACCOUNT_REGISTER: '/account-register',
  ACCOUNT_FORGET_PASSWORD: 'account-forgot-password',
  MY_ACCOUNT_ORDERS: '/my-orders',
  MY_ACCOUNT_WISHLIST: '/my-wishlist',
  MY_ACCOUNT_EDIT: '/account-edit',
  MY_ACCOUNT_NEWSLETTER: '/account-newsletter',
  ADDRESS_BOOK: '/account-address',
  MY_ACCOUNT_GIFT_CART: '/account-giftcart',
  MY_ACCOUNT_ANONYMISE: '/account-anonymise',
  CUSTOMER_SERVICE: '/customer-services',
  CMS_CONTACT: '/contact',
  COMPLAINT_INFORMATION: '/complaint_informations',
  HOW_TO_ORDER: '/how_to_orders',
  TERM: '/termss',
  PAYMENT_METHOD: '/payment_methods',
  SALES_OFFS: '/sale_offerss',
  RETURN: '/returnss',
  PRICE_MATCH: '/price_matchs',
  FAQ: '/faqs',
  FREE_DELIVERY: '/free_deliverys',
  COOKIES_POLICYS: '/cookies-policys',
  PRIVACYS: '/privacys',
  BUNK_BED: '/bunk-bed-guide-buyer-guides',
  BED_SIZESS: '/bed-sizess',
  TERM_OF_USES: '/terms-of-usess',
  ORDER_DETAIL: '/order-detail',
  CATALOG_SEARCH: '/catalog-search',
  SUGGESTIONSS: '/suggestionss',
  DAMANGESS: '/damagess',
});
