export class R_DEFAULT_VALUE {
  static PROXY_DEFAULT_URL_KEY = 'PROXY_DEFAULT_URL_KEY';
  static PCMS_DEFAULT_URL_KEY = 'PCMS_DEFAULT_URL_KEY';
  static PROXY_APP_NAME = 'PROXY_APP_NAME';

  // client id để authen với api
  static CLIENT_ID_KEY = 'CLIENT_ID_KEY';

  static GRAPHQL_DEFAULT_URL_KEY = 'GRAPHQL_DEFAULT_URL_KEY';
  static GRAPHQL_BACKEND_URL_KEY = 'GRAPHQL_BACKEND_URL_KEY';
  static GRAPHQL_DEFAULT_HEADER_KEY = 'GRAPHQL_DEFAULT_HEADER_KEY';
  static GRAPHQL_RESOLVE_ADDITIONAL_HEADER_KEY =
    'GRAPHQL_RESOLVE_ADDITIONAL_HEADER_KEY';
  static ASYNC_STORAGE_INSTANCE_KEY = 'ASYNC_STORAGE_INSTANCE_KEY';
}
