-- AlterTable
ALTER TABLE "stock_trading_analysis" ADD COLUMN     "foreign_buy_15" SMALLINT NOT NULL DEFAULT 0,
ADD COLUMN     "foreign_buy_30" SMALLINT NOT NULL DEFAULT 0,
ADD COLUMN     "foreign_buy_7" SMALLINT NOT NULL DEFAULT 0,
ADD COLUMN     "foreign_diff_15" SMALLINT NOT NULL DEFAULT 0,
ADD COLUMN     "foreign_diff_30" SMALLINT NOT NULL DEFAULT 0,
ADD COLUMN     "foreign_diff_7" SMALLINT NOT NULL DEFAULT 0,
ADD COLUMN     "foreign_sell_15" SMALLINT NOT NULL DEFAULT 0,
ADD COLUMN     "foreign_sell_30" SMALLINT NOT NULL DEFAULT 0,
ADD COLUMN     "foreign_sell_7" SMALLINT NOT NULL DEFAULT 0;
