name: Auto Merge master to deployment/stock/production

on:
  push:
    branches:
      - master

jobs:
  merge-to-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch and checkout to deployment/stock/production
        run: |
          git fetch origin deployment/stock/production
          git checkout deployment/stock/production

      - name: Pull the latest changes from master
        run: |
          git pull origin master --rebase

      - name: Merge master into deployment/stock/production
        run: |
          git config --global user.email "workflows@github.com"
          git config --global user.name "workflows"
          git merge master --no-edit
          git push origin deployment/stock/production
