name: Auto Merge master to deployment/stock/production

on:
  push:
    branches:
      - master

jobs:
  merge-to-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git User
        run: |
          git config --global user.email "workflows@github.com"
          git config --global user.name "workflows"

      - name: Fetch all branches
        run: |
          git fetch --all

      - name: Checkout to deployment/stock/production
        run: |
          git checkout deployment/stock/production

      - name: Merge master into deployment/stock/production
        run: |
          git config pull.rebase false
          git merge master --allow-unrelated-histories

      - name: Push master into deployment/stock/production
        run: |
          git push origin deployment/stock/production
